### ISSUE TITLE
Java out of memory error

### ISSUE THREAD

**Issue by willettk** [culturevis/imageplot#5]
I just downloaded ImagePlot for the first time and tried to run it on the sample files (plotting the Mondrian images). Attempts to run it result in the following error messages:

```
ImageJ 1.47t; Java 1.6.0_65 [32-bit]; Mac OS X 10.9.5; 5229K of 400MB (1%)
 
java.lang.OutOfMemoryError: Java heap space
	at ij.gui.NewImage.createRGBImage(NewImage.java:158)
	at ij.gui.NewImage.createImage(NewImage.java:296)
	at ij.IJ.createImage(IJ.java:1822)
	at ij.IJ.newImage(IJ.java:1879)
	at ij.macro.Functions.newImage(Functions.java:2803)
	at ij.macro.Functions.doFunction(Functions.java:153)
	at ij.macro.Interpreter.doStatement(Interpreter.java:219)
	at ij.macro.Interpreter.doStatements(Interpreter.java:207)
	at ij.macro.Interpreter.run(Interpreter.java:104)
	at ij.macro.Interpreter.run(Interpreter.java:74)
	at ij.macro.MacroRunner.run(MacroRunner.java:130)
	at java.lang.Thread.run(Thread.java:695)
```

I have a fairly high-performance MacBook Air with OS X 10.9.5 and 8 GB of RAM. What kind of memory requirements does ImagePlot have that result in this?

**Comment by ngopal** [comment]
I'm getting the same error. It says it's using less than 1%...

ImageJ 1.48v; Java 1.6.0_51 [64-bit]; Mac OS X 10.8.5; 4308K of 658MB (<1%)
 
java.lang.OutOfMemoryError: Java heap space
	at ij.gui.NewImage.createRGBImage(NewImage.java:154)
	at ij.gui.NewImage.createImage(NewImage.java:305)
	at ij.IJ.createImage(IJ.java:1861)
	at ij.IJ.newImage(IJ.java:1918)
	at ij.macro.Functions.newImage(Functions.java:2825)
	at ij.macro.Functions.doFunction(Functions.java:153)
	at ij.macro.Interpreter.doStatement(Interpreter.java:226)
	at ij.macro.Interpreter.doStatements(Interpreter.java:214)
	at ij.macro.Interpreter.runMacro(Interpreter.java:137)
	at ij.macro.MacroRunner.run(MacroRunner.java:152)
	at java.lang.Thread.run(Thread.java:680)

Perhaps updating Java will help?

**Comment by shosanna** [comment]
I am having the same problem even though I raised the memory limit to 5 GB (and yes, I restarted it :))
Please any help?

**Comment by wpkurtz** [comment]
Hi, all. I'm trying to up my memory (Edit > Options > Memory and Thread), but when I do, I'm getting an error message. I think it's saying that the directory is read-only, but I've tried running ImageJ in several different writeable directories (Desktop, Apps, Downloads) and I keep getting the same error. 
<img width="1334" alt="Screen Shot 2021-01-30 at 5 35 58 PM" src="https://user-images.githubusercontent.com/19156874/106372142-9e8c5680-6321-11eb-8a2c-d3386798ba75.png">

Suggestions most welcome!
